export const AUTH_LOADING = 'AUTH_LOADING'
export const AUTH_SUCCESS = 'AUTH_SUCCESS'
export const AUTH_ERROR = 'AUTH_ERROR'

export const SEARCH_LOADING = 'SEARCH_LOADING'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_ERROR = 'SEARCH_ERROR'
export const SEARCH_RESET = 'SEARCH_RESET'
export const SEARCH_SET_PARAMS = 'SEARCH_SET_PARAMS'
export const TOGGLE_TOOLTIP = 'TOGGLE_TOOLTIP'

export const SHOW_SAVE_FAVORITES = 'SHOW_SAVE_FAVORITES'
export const HIDE_SAVE_FAVORITES = 'HIDE_SAVE_FAVORITES'
export const GET_FAVORITES = 'GET_FAVORITES'
export const EDIT_FAVORITE = 'EDIT_FAVORITE'
export const REMOVE_FAVORITE = 'REMOVE_FAVORITE'

